---
# Domain Join Configuration
# Copy this file and change only the values marked with "CHANGE THIS"
# Sensitive values are automatically injected via GitHub secrets

# ===========================================
# CHANGE THESE VALUES (Only 5 settings to configure)
# ===========================================

# 1. Domain Information
domain:
  name: "cce3.gpc"                    # e.g., "company.local"
  admin_user: "{{ secrets.DOMAIN_ADMIN_USER }}"       # Set in GitHub Secrets
  admin_password: "{{ secrets.DOMAIN_ADMIN_PASSWORD }}" # Set in GitHub Secrets
  # Optional: Custom OU paths (leave as-is if using defaults)
  # Use OU where your admin user has delegation permissions
  # Note: Spaces in OU names are properly handled by the join commands
  linux_ou: "OU=VA,OU=DEV OU,DC=cce3,DC=gpc"  # Target OU for Linux computers
  windows_ou: "OU=Servers,DC=cce3,DC=gpc"

# 2. Target VM Information
target_vm:
  name: "gadvaappah01"                         # e.g., "web-server-01"
  name: "gadvaappah01"                         # e.g., "web-server-01"
  ip_address: "10.5.147.51"                     # e.g., "192.168.1.100"
  os_type: "linux"                           # Options: "linux" or "windows"
  description: "Last Refactor. Did it work?"                   # Description for AD computer account

# 3. Network Settings
network:
  dns_server: "gadvadc04.cce3.gpc"                    # e.g., "192.168.1.1"
  domain_controller: "gadvadc04.cce3.gpc"              # e.g., "192.168.1.10"

# 4. vCenter Connection (if using vCenter)
vcenter:
  host: "{{ secrets.VCENTER_HOSTNAME }}"              # Set in GitHub Secrets
  user: "{{ secrets.VCENTER_USERNAME }}"              # Set in GitHub Secrets
  password: "{{ secrets.VCENTER_PASSWORD }}"          # Set in GitHub Secrets
  port: "{{ secrets.VCENTER_PORT | default('443') }}"
  validate_certs: "{{ secrets.VCENTER_VALIDATE_CERTS | default('false') }}"

# ===========================================
# WORKFLOW CONFIGURATION (Don't modify these)
# ===========================================

# vCenter connectivity test
vcenter_test:
  playbook_path: "playbooks/validation/test_vcenter.yml"
  dry_run: false
  tags: "connectivity"
  target_hosts: "runner"

# Pre-flight checks
preflight_checks:
  playbook_path: "playbooks/validation/preflight_checks.yml"
  dry_run: false
  tags: "preflight"
  target_hosts: "runner"

# Main domain join automation
domain_join:
  playbook_path: "playbooks/site.yml"
  dry_run: false
  tags: "domain_join"
  target_hosts: "linux_vms"

# Post-join validation
domain_validation:
  playbook_path: "playbooks/provisioning/testing/domain_validation.yml"
  dry_run: false
  tags: "validation"
  target_hosts: "linux_vms"

# ===========================================
# ANSIBLE VARIABLES (Auto-generated by workflow)
# ===========================================

# The vm_config variables are automatically generated by the workflow
# from the target_vm, domain, and network sections above.
# No need to maintain them manually - they're created at runtime!