---
# ===================================================================================
# Network: GADHQVMESDS11-Green-hq — subnet and host‑level configuration
# ===================================================================================

config_vm_network: "xxxxxxxxxxx01-Green-xx.xx.xx.xx"
config_vm_network_dns_servers: "xx.xx.xx.xx"
config_vm_network_gateway: "xx.xx.xx.xx"
config_vm_network_netmask: "xx.xx.xx.xx"

# Per‑host derived values
config_vm_name: "{{ inventory_hostname }}"
config_vm_network_start_ip: "{{ ansible_host }}"
config_vm_network_end_ip: "{{ ansible_host }}"
# config_vm_network_domain: "{{ config_vm_domain }}"

# Default VM sizing
#config_vm_memory_mb: 4096
#config_vm_cpu_count: 2
#config_vm_disk_size_gb: 60
#config_vm_disk_type: "thin"
